# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Inicio"
  url = "#hero"
  weight = 5
  
[[main]]
  name = "¿Quién soy?"
  url = "#"
  weight = 10
  hasChildren = true

[[main]]
  parent = "¿Quién soy?"
  name = "Bio"
  weight = 11
  url = "#about"

[[main]]
  parent = "¿Quién soy?"
  name = "Destrezas y defectos"
  weight = 12
  url = "#skills"

[[main]]
  parent = "¿Quién soy?"
  name = "CV"
  weight = 13
  url = "#experience"

[[main]]
  parent = "¿Quién soy?"
  name = "Cosicas para presumir"
  weight = 14
  url = "#accomplishments"
  
[[main]]
  name = "Temas"
  url = "#tags"
  weight = 20
  
# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 30

[[main]]
  name = "Cursos"
  url = "#cursos"
  weight = 40
  
  
# [[main]]
#   name = "Cursos(mal)"
#   url = "courses/"
#   weight = 45
  
[[main]]
  name = "Medios y eventos"
  url = "#"
  weight = 50
  hasChildren = true
  
[[main]]
  parent = "Medios y eventos"
  name = "Eventos"
  weight = 51
  url = "#talks"
  
[[main]]
  parent = "Medios y eventos"
  name = "Aparición en medios"
  weight = 52
  url = "#medios"
  
[[main]]
  name = "Artículos científicos"
  url = "#publications"
  weight = 60
  
[[main]]
  name = "Redes"
  url = "#"
  weight = 70
  hasChildren = true

[[main]]
  parent = "Redes"
  name = "🚨 Patreon"
  weight = 71
  url = "https://patreon.com/dadosdelaplace"

[[main]]
  parent = "Redes"
  name = "🚨 Newsletter"
  weight = 72
  url = "https://cartasdelaplace.susbtack.com"
  
[[main]]
  parent = "Redes"
  name = "Contacto"
  weight = 73
  url = "#contact"
  
[[main]]
  parent = "Redes"
  name = "Twitter"
  weight = 74
  url = "https://twitter.com/dadosdelaplace"
  
[[main]]
  parent = "Redes"
  name = "Instagram"
  weight = 75
  url = "https://instagram.com/javieralvarezliebana"

[[main]]
  parent = "Redes"
  name = "Discord"
  weight = 76
  url = "https://discord.gg/RpXRqTgGdt"

[[main]]
  parent = "Redes"
  name = "Telegram"
  weight = 77
  url = "https://t.me/dadosdelaplace"

[[main]]
  parent = "Redes"
  name = "Github"
  weight = 78
  url = "github.com/dadosdelaplace"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
