title: Javier Álvarez Liébana
baseURL: https://examplesite.org
copyright: Copyright &copy; {year} - Javier Álvarez Liébana (Dados de Laplace)
googleAnalytics: ''
disqusShortname: ''
theme: academia-hugo
enableGitInfo: yes
defaultContentLanguage: es
hasCJKLanguage: no
defaultContentLanguageInSubdir: yes
removePathAccents: yes
paginate: 7
enableEmoji: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
blackfriday:
  angledQuotes: no
  extensions: backslashLineBreak
  hrefTargetBlank: yes
  latexDashes: yes
imaging:
  anchor: smart
  quality: 90
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
